# Matrizes Triangulares

In [1]:
import numpy as np
import bruno as br  # Importando suas funções

def check_input_matrix_vector(matrix, x):
    """Verifica se a matriz é quadrada e se o vetor tem comprimento correto."""
    assert matrix.shape[0] == matrix.shape[1], "A matriz deve ser quadrada."
    assert isinstance(x, np.ndarray) and x.ndim == 1, "O vetor x deve ser 1D."
    assert matrix.shape[0] == len(x), "O comprimento do vetor deve ser igual ao tamanho da matriz."

def matvec_triu_prod3(U, x, check_input=True):
    '''
    Compute the product of an upper triangular matrix U 
    and a vector x. All elements are real numbers.
    
    Each element of the resultant vector is obtained by 
    computing a dot product.
    '''
    if check_input:
        assert U.shape[0] == U.shape[1], "Matrix must be square"
        assert x.ndim == 1, "x must be a 1D array"
        assert U.shape[0] == x.shape[0], "Matrix dimensions must match vector length"

    N = U.shape[0]
    y = np.zeros(N)
    
    for i in range(N):
        y[i] = br.dot_real(U[i, i:], x[i:])
    
    return y


def matvec_triu_prod5(U, x, check_input=True):
    '''
    Compute the product of an upper triangular matrix U 
    and a vector x. All elements are real numbers.
    
    The elements of the resultant vector are obtained by 
    computing successive scalar vector products.
    '''
    if check_input:
        assert U.shape[0] == U.shape[1], "Matrix must be square"
        assert x.ndim == 1, "x must be a 1D array"
        assert U.shape[0] == x.shape[0], "Matrix dimensions must match vector length"

    N = U.shape[0]
    y = np.zeros(N)
    
    for j in range(N):
        y[:j+1] += br.scalar_vec_real(x[j], U[:j+1, j])
    
    return y

def matvec_tril_prod8(L, x, check_input=True):
    '''
    Compute the product of a lower triangular matrix L 
    and a vector x. All elements are real numbers.
    
    Each element of the resultant vector is obtained by 
    computing a dot product between the current row of L 
    and the portion of x corresponding to the indices.

    Parameters
    ----------
    L : numpy array 2d
        Lower triangular matrix.
    x : numpy array 1d
        Vector that postmultiply the triangular matrix L.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Vector obtained from the product L x.
    '''
    if check_input:
        assert L.shape[0] == L.shape[1], "Matrix must be square"
        assert x.ndim == 1, "x must be a 1D array"
        assert L.shape[0] == x.shape[0], "Matrix dimensions must match vector length"

    N = L.shape[0]
    z = np.zeros(N)
    
    for i in range(N):
        z[i] = br.dot_real(L[i, :i], x[:i])
    
    return z

def matvec_tril_prod10(L, x, check_input=True):
    '''
    Compute the product of a lower triangular matrix L 
    and a vector x. All elements are real numbers.
    
    The elements of the resultant vector are obtained 
    by computing successive scalar vector products.

    Parameters
    ----------
    L : numpy array 2d
        Lower triangular matrix.
    x : numpy array 1d
        Vector that postmultiply the triangular matrix L.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Vector obtained from the product L x.
    '''
    if check_input:
        assert L.shape[0] == L.shape[1], "Matrix must be square"
        assert x.ndim == 1, "x must be a 1D array"
        assert L.shape[0] == x.shape[0], "Matrix dimensions must match vector length"

    N = L.shape[0]
    z = np.zeros(N)
    
    for j in range(N):
        z[j:] += br.scalar_vec_real(x[j], L[j:, j])
    
    return z


In [2]:
# Gera uma matriz triangular superior aleatória
def generate_upper_triangular_matrix(n, random_seed=None):
    np.random.seed(random_seed)
    matrix = np.random.rand(n, n)
    return np.triu(matrix)  # Retorna apenas os elementos da triangular superior

# Gera uma matriz triangular inferior aleatória
def generate_lower_triangular_matrix(n, random_seed=None):
    np.random.seed(random_seed)
    matrix = np.random.rand(n, n)
    return np.tril(matrix)  # Retorna apenas os elementos da triangular inferior

def generate_random_vector(n, random_seed=None):
    np.random.seed(random_seed)
    return np.random.rand(n)

In [3]:
U3 = generate_upper_triangular_matrix(3)
v3 = generate_random_vector(3)

In [4]:
matvec_triu_prod3(U3, v3)

array([0.79613792, 0.78229711, 0.56965056])

In [5]:
matvec_triu_prod5(U3, v3)

array([0.79613792, 0.78229711, 0.56965056])

In [6]:
L3 = generate_lower_triangular_matrix(3)

In [7]:
matvec_tril_prod8(L3, v3)

array([0.        , 0.00619114, 0.37771922])

In [8]:
matvec_tril_prod10(L3, v3)

array([5.51925032e-04, 5.53516950e-02, 6.18187703e-01])

### Comparando Ux = v  ----> Triu_system ----> Triangular_superior

In [9]:
x= br.triangular_superior(U3, v3)
x

array([-0.92943031,  0.03469383,  0.99285158])

In [10]:
x1 = np.linalg.solve(U3, v3)
x1

array([-0.92943031,  0.03469383,  0.99285158])

### Comparando Lx = v -----> Tril_system -----> Triangular_inferior

In [11]:
x= br.triangular_inferior(L3, v3)
x

array([ 1.49222126,  2.49915192, -5.01339421])

In [12]:
x1 = np.linalg.solve(L3, v3)
x1

array([ 1.49222126,  2.49915192, -5.01339421])