# Eliminação de Gauss

In [1]:
import bruno
import numpy as np

In [2]:
A = np.array([[2.,1.,-1.],
              [-3.,-1.,2.],
              [-2.,1.,2.]])


y = np.array([8., -11., -3.])

In [3]:
u, b=bruno.Gauss_elim(A, y)
np.linalg.solve(u, b)

array([ 2.,  3., -1.])

In [4]:
t1 = np.linalg.solve(A, y)
t1

array([ 2.,  3., -1.])

In [5]:
t2 = bruno.triangular_superior(u, b)
t2

array([ 2.,  3., -1.])

In [6]:
print("True" if np.allclose(t1 ,t2 , rtol =1) else "False") # tolerancia de uma casa decimal

True


In [7]:
print(type(t1), type(t2))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


### N = 8 elementos

In [8]:
A = np.array([[4, 1, -2, 3, 0, 7, 2, 5],
              [2, 5, 0, -1, 4, 3, 6, -2],
              [0, 4, 3, 1, -5, 2, 7, 0],
              [1, 0, 5, 4, 2, 6, -3, 3],
              [3, 2, 6, 0, 5, -1, 4, 1],
              [-2, 1, 0, 3, 6, 4, 1, 2],
              [5, 4, -1, 2, 3, 0, 7, 6],
              [2, 6, 3, 5, -2, 1, 4, 0]], dtype=float)

x = np.array([10, -2, 8, 7, 5, -3, 4, 6], dtype=float)

In [9]:
U, b = bruno.Gauss_elim(A, x)

In [10]:
print(U)

[[ 4.00000000e+00  1.00000000e+00 -2.00000000e+00  3.00000000e+00
   0.00000000e+00  7.00000000e+00  2.00000000e+00  5.00000000e+00]
 [ 0.00000000e+00  4.50000000e+00  1.00000000e+00 -2.50000000e+00
   4.00000000e+00 -5.00000000e-01  5.00000000e+00 -4.50000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.11111111e+00  3.22222222e+00
  -8.55555556e+00  2.44444444e+00  2.55555556e+00  4.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.36842105e+00
   2.47368421e+01 -2.21052632e+00 -9.94736842e+00 -9.02631579e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -2.48039216e+01 -9.29411765e+00  1.56764706e+01  5.96568627e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -6.26956522e+00  9.28695652e+00  4.12608696e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -4.44089210e-16  0.00000000e+00 -1.00159501e+01 -2.31733073e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -

In [11]:
bruno.triangular_superior(U, b)

array([ 1.57343216, -2.33489651,  0.71631945,  1.51180125, -0.68578496,
        0.5187449 ,  1.31605884, -0.6649858 ])

In [12]:
np.linalg.solve(U, b)

array([ 1.57343216, -2.33489651,  0.71631945,  1.51180125, -0.68578496,
        0.5187449 ,  1.31605884, -0.6649858 ])

In [13]:
np.allclose(bruno.triangular_superior(U, b), np.linalg.solve(U, b), rtol=5 ) # tolerancia de 5 casas decimais

True

### Testando a matriz do exemplo de aula

In [14]:
A = np.array([[ 2., 1.,-1.],
              [-3.,-1., 2.],
              [-2., 1., 2.]])
y = np.array([8., -11., -3.])

### Testar a Função de Permutação:

In [15]:
ba1 = bruno.permut(A, 0)

In [16]:
I = np.identity(A.shape[0])
print('I = ', '\n', I, '\n')
P1 = I[[1,0,2]]
print('P1 = ', '\n', P1, '\n')
A1 = P1@A
print('A1 = ', '\n',A1, '\n')
#Tetando se as matrizes são parecidas
for r in range(0, len(y)):
    print(np.allclose(ba1[1][r][:], A1[r][:], rtol = 1e8))

I =  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

P1 =  
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] 

A1 =  
 [[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]] 

True
True
True


In [17]:
ba2 = bruno.permut(A, 1)
I = np.identity(A.shape[0])
print('I = ', '\n', I, '\n')
print('Perm 2 = ', '\n', ba2[1], '\n')
P2 = I[[0,2,1]]
print('P2 = ', '\n', P2, '\n')
A2 = P2@A
print('A2 = ', '\n',A2, '\n')
#Tetando se as matrizes são parecidas
for r in range(0, len(y)):
    print(np.allclose(ba2[1][r][:], A2[r][:], rtol = 1e8))

I =  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Perm 2 =  
 [[-3. -1.  2.]
 [ 2.  1. -1.]
 [-2.  1.  2.]] 

P2 =  
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] 

A2 =  
 [[-3. -1.  2.]
 [-2.  1.  2.]
 [ 2.  1. -1.]] 

True
True
True


In [18]:
ba3 = bruno.permut(A2, 1)
I = np.identity(A.shape[0])
print('I = ', '\n', I, '\n')
print('Perm 3 = ', '\n', ba3[1], '\n')
P3 = I[[1,2,0]]
print('P3 = ', '\n', P3, '\n')
A3 = P3@A
print('A3 = ', '\n',A3, '\n')
#Tetando se as matrizes são parecidas
for r in range(0, len(y)):
    print(np.allclose(ba3[1][r][:], A3[r][:], rtol = 1e8))

print('PP3 = ', '\n',I[ba3[0]], '\n')

I =  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Perm 3 =  
 [[-3. -1.  2.]
 [-2.  1.  2.]
 [ 2.  1. -1.]] 

P3 =  
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

A3 =  
 [[ 2.  1. -1.]
 [-2.  1.  2.]
 [-3. -1.  2.]] 

True
True
True
PP3 =  
 [0. 1. 0.] 



###### Verifica que a função permut não ficou muito parecido para esse exemplo de matriz $P_n[\vec{p}]$, uma vez que duas linhas delas são iguais em modulo, pois ele verifica o pivo maximo de cada linha. Indices diferente de zero, ele não permuta. 

### Crie um sistema linear e seu sistema triangular equivalente manualmente (sem usar Gauss_elim).

## Seja o sistema linear Ax = b, onde 
A =\begin{bmatrix}
2 & 1 & -1 & 2 \\
4 & 5 & -3 & 6 \\
-2 & 5 & -2 & 6 \\
4 & 11 & -4 & 8
\end{bmatrix} 
b = \begin{bmatrix}
0 \\
0 \\
1 \\
2
\end{bmatrix}
## O seu sistema trinangular equivalente é Ux = b_mod
U = \begin{bmatrix}
2 & 1 & -1 & 2 \\
0 & 3 & -1 & 2 \\
0 & 0 & -1 & 4 \\
0 & 0 & 0 & 2
\end{bmatrix}

b_mod = \begin{bmatrix}
0 \\
0 \\
1 \\
3
\end{bmatrix}

### Vamos Usar a função Gauss_elim para calcular o sistema triangular equivalente.

In [19]:
A =np.array([
[2 , 1 , -1 , 2],
[4 , 5 , -3 , 6],
[-2 , 5 , -2 , 6],
[4 , 11 , -4 , 8]])

B = np.array([0,0,1,2])

U_verdadeiro = np.array([
[ 2.,  1., -1.,  2.],
[ 0.,  3., -1.,  2.],
[ 0.,  0., -1.,  4.],
[ 0.,  0.,  0.,  2.]])

b_verdadeiro = np.array([0., 0., 1., 3.])

In [20]:
U, b_mod = bruno.Gauss_elim(A, B)

In [21]:
U

array([[ 2.,  1., -1.,  2.],
       [ 0.,  3., -1.,  2.],
       [ 0.,  0., -1.,  4.],
       [ 0.,  0.,  0.,  2.]])

In [22]:
b_mod

array([0., 0., 1., 3.])

In [23]:
bruno.triangular_superior(U, b_mod)

array([0.66666667, 0.66666667, 5.        , 1.5       ])

In [24]:
np.linalg.solve(A, B)

array([0.66666667, 0.66666667, 5.        , 1.5       ])

#### Comparando o calculado com o verdadeiro

In [25]:
np.allclose(U_verdadeiro, U)

True

In [26]:
np.allclose(b_verdadeiro, b_mod)

True

### Veficando assim, que o sistema calculado bate com o verdadeiro!

### Crie uma matriz $A_0$ e um vetor $\vec{x_0}$ e use-os para calcular um vetor $A_0\vec{x_0} = \vec{y_0}$. Então, use a função *Gauss_elim* para calcular o sistema triangular equivalente. Use uma de suas funções para calcular um vetor $\vec{x1}$ resolvendo o sistema triangular equivalente. Finalmente, compare o vetor calculado $\vec{x_1}$ e o vetor esperado $\vec{x_0}$.

In [27]:
A0 = np.array([
[2, 4, -2, 4], 
[1, 5, 5, 11],
[-1,-3,-2,-4] , 
[2, 6, 6, 8]])  

x0 = np.array([1,2,3,4])

y0 = bruno.matvec_real(A0, x0)

In [28]:
U, b_mod = bruno.Gauss_elim(A0, y0)

In [29]:
print('U:',U, '\t', 'b_mod: ', b_mod)

U: [[ 2.  4. -2.  4.]
 [ 0.  3.  6.  9.]
 [ 0.  0. -1.  1.]
 [ 0.  0.  0.  2.]] 	 b_mod:  [20. 60.  1.  8.]


In [30]:
x1 = bruno.triangular_superior(U, b_mod)

In [31]:
######### comparando X1 com X0 (vetor original)
print(np.allclose(x0, x1), ': x0 = x1')
print('x1: ', x1)

True : x0 = x1
x1:  [1. 2. 3. 4.]


In [32]:
y = bruno.matvec_real(A, x0)

In [33]:
U, b, L = bruno.Gauss_elim(A0, y, Mat_L=True)

In [34]:
bruno.triangular_superior(U, b)

array([ 583.83333333, -352.83333333,   49.        ,   87.66666667])

In [35]:
b

array([  9.        ,  24.5       ,  38.66666667, 175.33333333])

In [36]:
U

array([[ 2.,  4., -2.,  4.],
       [ 0.,  3.,  6.,  9.],
       [ 0.,  0., -1.,  1.],
       [ 0.,  0.,  0.,  2.]])

In [37]:
print(L)

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [-0.5        -0.33333333  1.          0.        ]
 [ 1.          0.66666667 -4.          1.        ]]


In [38]:
np.linalg.solve(A, y)

array([1., 2., 3., 4.])

In [39]:
x = bruno.triangular_inferior(L, y)
x

array([  9.        ,  24.5       ,  38.66666667, 175.33333333])

In [40]:
bruno.triangular_superior(U, x)

array([ 583.83333333, -352.83333333,   49.        ,   87.66666667])

In [41]:
L@U

array([[ 2.,  4., -2.,  4.],
       [ 1.,  5.,  5., 11.],
       [-1., -3., -2., -4.],
       [ 2.,  6.,  6.,  8.]])

### Tentando fazer por pivotamento (Troca de linhas).

In [42]:
def permut(C, i):
    """
    Função de permutação para realizar a troca de linhas, garantindo que o pivô seja o maior valor absoluto.
    
    Parâmetros:
    -----------
    C : numpy.ndarray
        Matriz aumentada (A e y empilhados).
    
    i : int
        Índice atual do passo da eliminação.
    
    Retorna:
    --------
    p : list
        Vetor de permutação.
    
    C : numpy.ndarray
        Matriz C com as linhas permutadas.
    """
    # Vetor de índices de permutação
    p = [j for j in range(C.shape[0])]
    
    # Encontra o índice do maior valor absoluto na coluna i a partir da linha i
    imax = i + np.argmax(np.abs(C[i:, i]))
    
    # Se o maior valor não estiver na linha atual, troca as linhas
    if imax != i:
        p[i], p[imax] = p[imax], p[i]
    
    # Retorna o vetor de permutação e a matriz permutada
    return p, C[p, :]

def Gauss_elim(A, y, check_input=True):
    """
    Executa a eliminação Gaussiana com pivotamento parcial para resolver o sistema Ax = y.
    
    Parâmetros:
    -----------
    A : numpy.ndarray
        Matriz quadrada do sistema linear.
    
    y : numpy.ndarray
        Vetor independente do sistema linear.
    
    check_input : boolean, opcional
        Se True, verifica se as entradas são válidas. O padrão é True.
    
    Retorna:
    --------
    Uper : numpy.ndarray
        Matriz triangular superior do sistema equivalente.
    
    b_mod : numpy.ndarray
        Vetor independente modificado após a eliminação.
    """
    N = A.shape[0]  # Número de linhas/colunas da matriz A
    
    if check_input is True:
        assert A.ndim == 2, 'A deve ser uma matriz'
        assert y.ndim == 1, 'y deve ser um vetor'
        assert A.shape[1] == N, 'A deve ser quadrada'
        assert y.size == N, 'O tamanho de y deve ser igual ao número de colunas de A'
    
    # Cria a matriz C empilhando A e y como uma matriz aumentada
    C = np.hstack((A, y.reshape(-1, 1)))

    for k in range(N - 1):
        # Passo de permutação para garantir que o maior pivô esteja na linha atual
        p, C = permut(C, k)
        
        # Verifica se o pivô não é zero
        assert C[k, k] != 0., 'Pivô nulo encontrado!'
        
        # Calcula os multiplicadores de Gauss e armazena na parte inferior da coluna
        C[k + 1:, k] = C[k + 1:, k] / C[k, k]
        
        # Zera os elementos da coluna abaixo do pivô
        C[k+1:, k+1:] -=  np.outer(C[k + 1:, k], C[k, k + 1:])
    
    # Retorna a matriz triangular superior e o vetor independente modificado
    return C[:, :N], C[:, N]

In [43]:
U, b = Gauss_elim(A, y)

In [44]:
U

array([[ 4.        ,  5.        , -3.        ,  6.        ],
       [-0.5       ,  7.5       , -3.5       ,  9.        ],
       [ 1.        ,  0.8       ,  1.8       , -5.2       ],
       [ 0.5       , -0.2       , -0.11111111,  0.22222222]])

In [45]:
b

array([ 29.        ,  40.5       , -15.4       ,   0.88888889])

##### Vemos um erro na solução, pois o U n é um triangular superior

In [296]:
def Gauss_elim(A, x, check_input=True, low=False):
    """
    Executa a eliminação Gaussiana em uma matriz quadrada A e vetor x para resolver o sistema linear Ax = b.
    
    Parâmetros:
    -----------
    A : np.ndarray
        Matriz quadrada 2D (NxN) representando os coeficientes do sistema linear.
        
    x : np.ndarray
        Vetor 1D (N) representando o vetor do lado direito do sistema Ax = b.
        
    check_input : bool, opcional
        Se True, verifica se as entradas são válidas, incluindo a verificação de que A é uma matriz 2D 
        e x é um vetor 1D, além de garantir que ambos contenham apenas números reais. 
        O padrão é True.
    
    Retornos:
    ---------
    Uper : np.ndarray
        Matriz 2D (NxN) resultante da eliminação Gaussiana, onde Uper é a matriz triangular superior.
    
    b : np.ndarray
        Vetor 1D (N) modificado correspondente ao vetor do lado direito após a eliminação Gaussiana.
    
    L : np.ndarray, opcional
        Matriz 2D (NxN) resultante dos multiplicadores de Gauss, onde L é a matriz triangular inferior.
    """
    N = A.shape[0]  # Número de linhas
    Uper = np.copy(A)
    b = np.copy(x)
    I = np.identity(N)
    L = np.identity(N)  # L inicia como identidade
    P = np.identity(N)
    
    if check_input:
        assert isinstance(A, np.ndarray) and A.ndim == 2, 'A deve ser uma matriz 2D'
        assert isinstance(x, np.ndarray) and b.ndim == 1, 'x deve ser um vetor 1D'
        # Verifica se A e b contêm apenas números reais
        assert np.isrealobj(A), 'A deve conter apenas números reais'
        assert np.isrealobj(x), 'x deve conter apenas números reais'

    for k in range(N - 1):
        # Criação do vetor u_k
        u_k = np.zeros(N)
        u_k[k] = 1
        
        # Pivotamento
        p, Uper = permut(Uper, k)
        b = b[p]  # Reordena o vetor b de acordo com a permutação
        P = P[p, :]  # Acumula a permutação na matriz P
        
        assert Uper[k, k] != 0., 'Pivô nulo encontrado!'
        
        # Criação do vetor t_k
        t_k = np.zeros(N)
        for i in range(k + 1, N):
            t_k[i] = Uper[i, k] / Uper[k, k]

        # Calcula a matriz M e faz a atualização
        M = bruno.outer_real(t_k, u_k)
        Uper = bruno.matmat_real_dot(I - M, Uper)
        b = bruno.matvec_real_simple(I - M, b)

        # Acumula as operações de eliminação para construir a matriz L
        L = bruno.matmat_real_dot(L, I + M)

    if low == False:
        return Uper, b, P
    else:
        return Uper, b, P, L, p

In [297]:
U, b, P, L, p= Gauss_elim(A0, y0, low=True)

In [298]:
U

array([[ 2. ,  4. , -2. ,  4. ],
       [ 0. ,  3. ,  6. ,  9. ],
       [ 0. ,  0. ,  4. , -2. ],
       [ 0. ,  0. ,  0. ,  0.5]])

In [299]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [-0.5       , -0.33333333,  1.        ,  0.        ],
       [ 1.        ,  0.66666667, -0.25      ,  1.        ]])

#### Para o sistema $$Ax =b $$ onde P é uma matriz de permutação $$PA = LU $$ e assim $LUx = Pb$

In [300]:
P@A == L@U

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [301]:
P

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [302]:
P_novo = np.identity(A.shape[0])
P_novo = P_novo[[0,1,3, 2]]
P_novo

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [303]:
P_novo@A 

array([[ 2.,  1., -1.,  2.],
       [ 4.,  5., -3.,  6.],
       [ 4., 11., -4.,  8.],
       [-2.,  5., -2.,  6.]])

In [304]:
A 

array([[ 2,  1, -1,  2],
       [ 4,  5, -3,  6],
       [-2,  5, -2,  6],
       [ 4, 11, -4,  8]])

In [305]:
L@U

array([[ 2.,  4., -2.,  4.],
       [ 1.,  5.,  5., 11.],
       [-1., -3.,  3., -7.],
       [ 2.,  6.,  1., 11.]])

In [306]:
P_novo = P_novo[[0,1,2, 3]]
P_novo

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [307]:
P_novo.T@A == L@U

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [308]:
########################

In [328]:
U, b, P, L,p = Gauss_elim(A, y0,low=True)

In [329]:
U

array([[ 2. ,  4. , -2. ,  4. ],
       [ 0. ,  3. ,  6. ,  9. ],
       [ 0. ,  0. ,  4. , -2. ],
       [ 0. ,  0. ,  0. ,  0.5]])

In [330]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [-0.5       , -0.33333333,  1.        ,  0.        ],
       [ 1.        ,  0.66666667, -0.25      ,  1.        ]])

In [338]:
bruno.triangular_inferior(L, y0) == b[p]

array([ True,  True, False, False])

In [336]:
bruno.triangular_superior(U, bruno.triangular_inferior(L, y0))

array([ 26.5, -14.5,   4.5,   8.5])

In [337]:
A[p] == L@U

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [339]:
bruno.triangular_inferior(L, y0)

array([20.  , 60.  ,  1.  ,  4.25])

In [341]:
b[p]

array([20., 60.,  2.,  4.])

In [344]:
np.round(bruno.triangular_inferior(L, y0), 0) == b[p]

array([ True,  True, False,  True])

In [345]:
np.round(bruno.triangular_inferior(L, y0), 0)

array([20., 60.,  1.,  4.])