## Decomposição LU

In [1]:
import bruno
import numpy as np

In [2]:
A = np.array([[5, 15, 40, 5],
            [20, 10, 30, 15],
            [1, 5, 3, 9],
            [3, 15, 40, 20]])
d = np.array([1,0,5,3])

In [3]:
C = bruno.lu_decomp(A, d)

In [4]:
x = bruno.lu_solve(C, d )

In [5]:
A@x

array([ 1.00000000e+00, -3.55271368e-15,  5.00000000e+00,  3.00000000e+00])

In [6]:
np.allclose(d, A@x, rtol = 10) # tolerancia de 10 casa deciamis

True

In [7]:
print('d: ', d, ' & ', np.round(A@x))

d:  [1 0 5 3]  &  [ 1. -0.  5.  3.]


#### Verificando se A = LU 

In [8]:
A_calc = bruno.matmat_real_dot(C[0], C[1]) # C[0] = L, C[1]  = U
A_calc

array([[ 5., 15., 40.,  5.],
       [20., 10., 30., 15.],
       [ 1.,  5.,  3.,  9.],
       [ 3., 15., 40., 20.]])

In [9]:
np.allclose(A_calc, A, rtol = 20) # Tolerancia de 20 casa decimais

True

#### Comparando a solução do sistema linear obtido através de  lu_solve com o  numpy.linalg.solve

In [10]:
np.allclose(np.linalg.solve(A, d), x) #tolerancia 1e8

True

In [11]:
print('x_numpy:', np.linalg.solve(A, d), ' & ', 'x_calculado:', x)

x_numpy: [-0.05633803  1.         -0.35868545  0.1258216 ]  &  x_calculado: [-0.05633803  1.         -0.35868545  0.1258216 ]


### usando um exemplo randomico 

In [12]:
# Define o tamanho da matriz
n = 4

# Gera uma matriz quadrada nxn com elementos inteiros aleatórios entre -10 e 10
B = np.random.randint(-10, 11, size=(n, n))

# Gera um vetor coluna nx1 com elementos inteiros aleatórios entre -10 e 10
f = np.random.randint(-10, 11, size=n)

In [13]:
z = bruno.lu_decomp(B, f)
w = bruno.lu_solve(z, f)
w

array([-0.8, -1.2,  0.2,  0.6])

In [14]:
f

array([-5,  3,  7, -8])

In [15]:
B

array([[  8,  -4,   1,  -6],
       [ -9,  -1,   0,  -9],
       [ -2,  -9,   3, -10],
       [ -2,  10,   9,   1]])

In [16]:
np.linalg.solve(B, f)

array([-0.8, -1.2,  0.2,  0.6])

In [17]:
B@w

array([-5.,  3.,  7., -8.])

### Definindo A0, x0, onde y0 = A0x0

In [18]:
# Definindo a matriz A0 e o vetor x0
A0 = np.array([[4, 3, 0, 0],
               [3, 4, -1, 0],
               [0, -1, 4, 3],
               [0, 0, 3, 4]])

x0 = np.array([1, 2, 3, 4])

# Calculando o vetor y0
y0 = bruno.matvec_dot(A0, x0)

# Usando a função lu_decomp para obter L e U
C = bruno.lu_decomp(A0, y0)

# Usando a função lu_solve para resolver o sistema LUx = y0
x1 = bruno.lu_solve(C, y0)

# Comparando o vetor x1 com o vetor esperado x0
print("Vetor original x0:", x0)
print("Vetor calculado x1:", x1)

# Verificando se x0 e x1 são iguais dentro de uma tolerância
tolerancia = 1e-9
np.allclose(x0, x1, atol=tolerancia)

Vetor original x0: [1 2 3 4]
Vetor calculado x1: [1. 2. 3. 4.]


True