# Test função de decomposição LU

In [1]:
import bruno 
import numpy as np

In [2]:
from bruno import lu_decomp_pivoting
from bruno import lu_solve_pivoting

## Nesse momento vamos fazer a decomposição A = LU 

In [3]:
A = np.array([[2., 1., 1.],
              [4., -6., 0.],
              [-2., 7., 2.]])

P, L, U = lu_decomp_pivoting(A, retornaLU=True)

In [4]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [-0.5,  1. ,  1. ]])

In [5]:
U

array([[ 4., -6.,  0.],
       [ 0.,  4.,  1.],
       [ 0.,  0.,  1.]])

In [6]:
np.allclose(A[P], L@U)

True

## Vamos definir um vetor qualquer que satisfaça a solução

In [7]:
Vec = np.array([16, 8, 2])

In [8]:
P, C = lu_decomp_pivoting(A)

In [9]:
r = lu_solve_pivoting(P = P, C= C, y = Vec)
r

array([ 8.75,  4.5 , -6.  ])

In [10]:
np.linalg.solve(A, Vec)

array([ 8.75,  4.5 , -6.  ])

### Sistema Ar = vec

In [11]:
bruno.matvec_dot(A, r)

array([16.,  8.,  2.])

In [12]:
np.allclose(Vec, A@r)

True

In [13]:
# Obter I[P] a partir da lista de permutações P
I = np.eye(A.shape[0])
I_P_custom = I[P]
I_P_custom

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [14]:
from scipy.linalg import lu
# Decomposição LU com scipy
P_scipy, L_scipy, U_scipy = lu(A)

In [15]:
P_scipy.T

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [16]:
np.allclose(I_P_custom, P_scipy.T)

True

### continuando 

In [27]:
# Definir a matriz A0 e o vetor x0
A0 = np.array([[3., 1., 2.],
               [6., 3., 4.],
               [3., 1., 5.]])

x0 = np.array([4., 2., 3.])

# Calcular o vetor y0 como A0 * x0
y0 = bruno.matvec_dot(A0 , x0)
y0

array([20., 42., 29.])

In [40]:
P1, C1 = lu_decomp_pivoting(A0)

In [41]:
x1 = lu_solve_pivoting(P=P1, C=C1, y=y0)
x1

array([4., 2., 3.])

In [42]:
diff = np.linalg.norm(x0 - x1)

In [43]:
diff

0.0

In [44]:
np.round(np.linalg.inv(A0)@A0, 16) # até a 15 casa é uma identidade

array([[ 1.e+00, -1.e-16, -2.e-16],
       [ 0.e+00,  1.e+00,  0.e+00],
       [ 0.e+00,  0.e+00,  1.e+00]])

In [45]:
np.linalg.det(A0)

8.999999999999998

In [46]:
bruno.minimos_quadrados(A0, y0)

array([4., 2., 3.])

In [47]:
np.linalg.solve(A0, y0)

array([4., 2., 3.])

### Esse sistema tem solução