# Cholesky

In [1]:
import numpy as np
import bruno as br

## Teste 1

In [2]:
# Definir uma matriz simétrica positiva definida
A = np.array([[4, 2, 2],
              [2, 3, 1],
              [2, 1, 2]])

In [3]:
# Calcular a decomposição de Cholesky
CH = br.cho_decomp(A)

In [4]:
CH

array([[2.        , 0.        , 0.        ],
       [1.        , 1.41421356, 0.        ],
       [1.        , 0.        , 1.        ]])

In [5]:
D = br.matmat_real_outer(CH, CH.T)

In [6]:
D

array([[4., 2., 2.],
       [2., 3., 1.],
       [2., 1., 2.]])

In [7]:
np.allclose(A, D)

True

In [8]:
# Definindo um vetor x
x = np.array([9, 1, 1])
y = br.matvec_real_simple(A, x)
y

array([40., 22., 21.])

In [9]:
w = br.matvec_dot(np.linalg.inv(CH), y)
w

array([20.        ,  1.41421356,  1.        ])

In [10]:
x1 = br.matvec_dot(np.linalg.inv(CH.T), w)
x1

array([9., 1., 1.])

## Teste 2

In [11]:
# Define uma matriz simétrica e positiva definida
A = np.array([[4, 2, 2],
              [2, 2, 1],
              [2, 1, 2]])

# Faz uma cópia da matriz A para testar
A1 = A.copy()

# Calcula a decomposição de Cholesky
G = br.cho_decomp_overwrite(A1)

# Verifica se A = G @ G.T
u = br.matmat_real_outer(G, G.T)
np.allclose(u, A)

True

In [12]:
u

array([[4., 2., 2.],
       [2., 2., 1.],
       [2., 1., 2.]])

In [13]:
A

array([[4, 2, 2],
       [2, 2, 1],
       [2, 1, 2]])

In [14]:
# Define um vetor x
x = np.array([1, 2, 3])

# Calcula o vetor y = A @ x
y = A @ x

# Faz uma cópia da matriz A para testar
A1 = A.copy()

# Calcula a decomposição de Cholesky
G = br.cho_decomp_overwrite(A1)

# Resolve o sistema triangular inferior G @ z = y
z = br.triangular_inferior(G, y)

# Resolve o sistema triangular superior G.T @ x1 = z
x1 = br.triangular_superior(G.T, z)

In [15]:
G

array([[2, 0, 0],
       [1, 1, 0],
       [1, 0, 1]])

In [16]:
x1

array([1., 2., 3.])

In [17]:
np.linalg.cholesky(A)

array([[2., 0., 0.],
       [1., 1., 0.],
       [1., 0., 1.]])

## Teste 3

In [21]:
# Teste 1: Verificar se A * Ainv é a matriz identidade
A = np.array([[4, 12, -16], 
              [12, 37, -43], 
              [-16, -43, 98]])  # Matriz simétrica e positiva definida

# Calcular a decomposição de Cholesky de A
G = br.cho_decomp(A)

# Calcular a inversa de A usando a função cho_inverse
Ainv = br.cho_inverse(G)

# Verificar o produto A @ Ainv e Ainv @ A
identity_AAinv = br.matmat_real_dot(A, Ainv)
identity_AinvA = br.matmat_real_dot(Ainv, A)

In [24]:
np.allclose(identity_AAinv, identity_AinvA, rtol = 10)

True

In [25]:
Ainv

array([[ 49.36111111, -13.55555556,   2.11111111],
       [-13.55555556,   3.77777778,  -0.55555556],
       [  2.11111111,  -0.55555556,   0.11111111]])

In [27]:
np.linalg.inv(A)

array([[ 49.36111111, -13.55555556,   2.11111111],
       [-13.55555556,   3.77777778,  -0.55555556],
       [  2.11111111,  -0.55555556,   0.11111111]])