In [4]:
import bruno 
import numpy as np

In [21]:
# Defina a matriz H e o vetor v (supondo que v tenha N dimensões)

H = np.array([[2, 1, 0], [1, 3, 1], [0, 1, 4]])  # Exemplo de matriz H
v = np.array([1, 2, 3])  # Exemplo de vetor v
N = v.shape[0] # Exemplo para uma matriz 3x3
# Defina a matriz de covariância Σ_v (diagonal para elementos não correlacionados)
sigma_v = 1  # Variância de v
Sigma_v = sigma_v ** 2 * np.eye(N)   # Matriz de covariância diagonal

# Calcule Σ_t = H Σ_v H^T
Sigma_t = Sigma_v @ np.dot(H,  H.T)  # @ é a multiplicação de matrizes 

# Exibir a matriz de covariância Σ_t
print("Matriz de Covariância Σ_t:")
print(Sigma_t)
H@H.T

Matriz de Covariância Σ_t:
[[ 5.  5.  1.]
 [ 5. 11.  7.]
 [ 1.  7. 17.]]


array([[ 5,  5,  1],
       [ 5, 11,  7],
       [ 1,  7, 17]])

In [17]:
bruno.variancia(v)

1.0

In [15]:
np.cov(v)*np.eye(N)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
bruno.mat_covariancia(H, v)

array([[ 5.,  5.,  1.],
       [ 5., 11.,  7.],
       [ 1.,  7., 17.]])

In [18]:
np.cov(v)*np.eye(N)@ np.dot(H, H.T)

array([[ 5.,  5.,  1.],
       [ 5., 11.,  7.],
       [ 1.,  7., 17.]])