### Aqui vamos testar a lógica por trás de um produto externo

In [5]:
import numpy as np

In [6]:
def outer_real_simple(x, y):
    N = x.size
    M = y.size
    R = np.zeros(shape=(N, M))
    assert x.ndim == 1, 'x deve ser um vetor 1D'
    assert y.ndim == 1, 'y deve ser um vetor 1D'
    for i in range(0, N):
        for j in range(0, M):
            R[i, j] = x[i]*y[j]
    return R

In [7]:
x = np.array([2,4,5, 2])
y = np.array([1,3,1])

In [8]:
print(outer_real_simple(x, y))

[[ 2.  6.  2.]
 [ 4. 12.  4.]
 [ 5. 15.  5.]
 [ 2.  6.  2.]]


In [9]:
print(np.outer(x, y))

[[ 2  6  2]
 [ 4 12  4]
 [ 5 15  5]
 [ 2  6  2]]


#### Aqui vamos fazer a norma 2 de uma matriz

In [14]:
a = np.array([[3,1,5], [2,2,2], [3,1,5]])

In [15]:
a

array([[3, 1, 5],
       [2, 2, 2],
       [3, 1, 5]])

In [21]:
d = a.T@a
d

array([[22, 10, 34],
       [10,  6, 14],
       [34, 14, 54]])

In [22]:
a.T

array([[3, 2, 3],
       [1, 2, 1],
       [5, 2, 5]])

In [74]:
np.linalg.norm(a, ord=2)

8.921186174671476

In [63]:
N, M  = a.shape
r = 0
for i in range(0, N):
    for j in range(0, M):
        r+= abs(a[j]*a[i])

In [64]:
r

array([ 64,  16, 144])

In [65]:
np.sqrt(82)

9.055385138137417

In [66]:
np.sqrt(np.trace(d))

9.055385138137417

In [75]:
np.sqrt(np.sum(a**2))

9.055385138137417