# Matriz - Matriz

In [1]:
import bruno
import numpy as np

def teste_matmat_real_entrada_diferente():
    try:
        A = np.array([[1, 2], [3, 4]])
        B = np.array([[1, 2, 3]])
        resultado = bruno.matmat_real_simple(A, B)
        print("teste_matmat_real_entrada_diferente falhou")
    except AssertionError:
        print("teste_matmat_real_entrada_diferente passou")

def teste_matmat_real_funcoes_comparar_numpy_dot():
    A = np.random.rand(3, 4)
    B = np.random.rand(4, 5)

    resultado_simples = bruno.matmat_real_simple(A, B)
    resultado_dot = np.dot(A, B)
    
    print(resultado_simples)
    print(resultado_dot)
    
    if np.allclose(resultado_simples, resultado_dot):
        print("teste_matmat_real_funcoes_comparar_numpy_dot passou")
    else:
        print("teste_matmat_real_funcoes_comparar_numpy_dot falhou")

def teste_matmat_real_funcoes_ignorar_complexo():
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])
    resultado_simples = bruno.matmat_real_simple(A, B)
    resultado_dot = np.dot(A, B)
    
    print(resultado_simples)
    print(resultado_dot)
    
    if np.allclose(resultado_simples, resultado_dot):
        print("teste_matmat_real_funcoes_ignorar_complexo passou")
    else:
        print("teste_matmat_real_funcoes_ignorar_complexo falhou")

def teste_matmat_complexo_comparar_numpy_dot():
    A = np.random.rand(3, 4) + 1j * np.random.rand(3, 4)
    B = np.random.rand(4, 5) + 1j * np.random.rand(4, 5)

    resultado_complexo = bruno.matmat_complex(A, B)
    resultado_dot = np.dot(A, B)
    
    print(resultado_complexo)
    print(resultado_dot)
    
    if np.allclose(resultado_complexo, resultado_dot):
        print("teste_matmat_complexo_comparar_numpy_dot passou")
    else:
        print("teste_matmat_complexo_comparar_numpy_dot falhou")

def teste_matmat_complexo_funcao_invalida():
    try:
        A = np.array([[1 + 1j, 2 + 2j], [3 + 3j, 4 + 4j]])
        B = np.array([[5 + 5j, 6 + 6j], [7 + 7j, 8 + 8j]])
        # Fornece uma entrada inválida ao passar uma matriz não compatível
        C = np.array([[1 + 1j, 2 + 2j, 3 + 3j]])  # Dimensões incompatíveis para multiplicação
        resultado = bruno.matmat_complex(A, C)
        print(resultado)
        print("teste_matmat_complexo_funcao_invalida falhou")
    except AssertionError:
        print("teste_matmat_complexo_funcao_invalida passou")
    except Exception as e:
        print(f"teste_matmat_complexo_funcao_invalida falhou com exceção: {e}")

In [2]:
# Executar os testes
teste_matmat_real_entrada_diferente()
teste_matmat_real_funcoes_comparar_numpy_dot()
teste_matmat_real_funcoes_ignorar_complexo()
teste_matmat_complexo_comparar_numpy_dot()
teste_matmat_complexo_funcao_invalida()

teste_matmat_real_entrada_diferente passou
[[0.6571769  0.2720606  0.29044195 0.86096035 0.75342443]
 [0.91640811 0.55537436 0.66703561 1.43706646 1.30761806]
 [1.26939617 1.08711412 1.39509212 2.11611612 1.92632181]]
[[0.6571769  0.2720606  0.29044195 0.86096035 0.75342443]
 [0.91640811 0.55537436 0.66703561 1.43706646 1.30761806]
 [1.26939617 1.08711412 1.39509212 2.11611612 1.92632181]]
teste_matmat_real_funcoes_comparar_numpy_dot passou
[[19. 22.]
 [43. 50.]]
[[19 22]
 [43 50]]
teste_matmat_real_funcoes_ignorar_complexo passou
[[-0.73153845+1.675182j   -0.25877881+2.40016442j -0.82160227+2.03245259j
  -1.06579351+2.66540555j -0.76476343+2.07853348j]
 [-0.29170201+1.22133233j  0.13899706+2.14518905j -0.42669713+1.91259444j
  -0.17875278+2.65117693j -0.01887177+2.06067267j]
 [ 0.11926255+1.61282992j  1.05357088+2.19563284j  0.3082432 +2.12948862j
   0.8664595 +2.48531981j  0.58228905+1.95340411j]]
[[-0.73153845+1.675182j   -0.25877881+2.40016442j -0.82160227+2.03245259j
  -1.06579351

In [3]:
A = np.array([[7, 14], [21, 7]])
B = np.array([[3, 2], [2, 3]])
C = np.array([[7 +2j, 14-1j], [21+1j, 7-2j]])

In [4]:
A@C

array([[343.+28.j, 196.-35.j],
       [294.+49.j, 343.-35.j]])

In [5]:
bruno.matmat_complex(A, C)

array([[343.+28.j, 196.-35.j],
       [294.+49.j, 343.-35.j]])

In [6]:
A@B

array([[49, 56],
       [77, 63]])

In [7]:
bruno.matmat_real_dot(A, B)

array([[49., 56.],
       [77., 63.]])

In [8]:
bruno.matmat_real_simple(A, B)

array([[49., 56.],
       [77., 63.]])

In [9]:
bruno.matmat_real_outer(A, B)

array([[49., 56.],
       [77., 63.]])

In [10]:
bruno.matmat_real_matvec(A, B)

array([[49., 56.],
       [77., 63.]])

In [11]:
bruno.matmat_real_columns(A, B)

array([[49., 56.],
       [77., 63.]])

In [19]:
bruno.matmat_real_columns(A.real, C.real)

array([[343., 196.],
       [294., 343.]])

In [21]:
bruno.matmat_real_dot(A.real, C.real)

array([[343., 196.],
       [294., 343.]])

In [14]:
np.dot(A, B)

array([[49, 56],
       [77, 63]])

In [15]:
np.dot(A, C)

array([[343.+28.j, 196.-35.j],
       [294.+49.j, 343.-35.j]])

In [22]:
bruno.matmat_real_outer(A.real, C.real)

array([[343., 196.],
       [294., 343.]])

In [23]:
bruno.matmat_real_matvec(A.real, C.real)

array([[343., 196.],
       [294., 343.]])

In [24]:
bruno.matmat_real_simple(A.real, C.real)

array([[343., 196.],
       [294., 343.]])

## Ignorando a parte complexa